services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME:-localstack-main}"
    image: localstack/localstack:3.8.1
    ports:
      - "${LOCALSTACK_PORT}:${LOCALSTACK_PORT}" # LocalStack Gateway
    environment:
      # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
      - DEBUG=${DEBUG:-0}
      - SERVICES=s3
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
    healthcheck:
      test: [ "CMD", "awslocal", "s3api", "wait", "bucket-exists", "--bucket", "${S3_BUCKET_NAME}" ]
      interval: 30s
      timeout: 10s
      retries: 5

  init-s3:
    image: localstack/localstack:3.8.1
    container_name: init-s3
    depends_on:
      - localstack
    entrypoint:
      - awslocal
      - --endpoint-url=http://${LOCALSTACK_URL}:${LOCALSTACK_PORT}
      - s3
      - mb
      - s3://${S3_BUCKET_NAME}

  event_generator:
    build:
      context: .
      dockerfile: src/event_generator/Dockerfile
    container_name: event_generator
    environment:
      - LOCALSTACK_PORT=${LOCALSTACK_PORT}
      - LOCALSTACK_URL=${LOCALSTACK_URL}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - S3_FILE_NAME=${S3_FILE_NAME}
      - AWS_KEY_ID=${AWS_KEY_ID}
      - AWS_SECRET=${AWS_SECRET}
    depends_on:
      localstack:
        condition: service_healthy

  webapp1:
    build:
      context: .
      dockerfile: src/web_app/Dockerfile
    environment:
      - LOCALSTACK_PORT=${LOCALSTACK_PORT}
      - LOCALSTACK_URL=${LOCALSTACK_URL}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - S3_FILE_NAME=${S3_FILE_NAME}
      - AWS_KEY_ID=${AWS_KEY_ID}
      - AWS_SECRET=${AWS_SECRET}
    deploy:
      resources:
        limits:
          memory: 512 M
      restart_policy:
        condition: any
    container_name: webapp1
    ports:
      - "5001:5050"
    depends_on:
      localstack:
        condition: service_healthy

  webapp2:
    build:
      context: .
      dockerfile: src/web_app/Dockerfile
    environment:
      - LOCALSTACK_PORT=${LOCALSTACK_PORT}
      - LOCALSTACK_URL=${LOCALSTACK_URL}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - S3_FILE_NAME=${S3_FILE_NAME}
      - AWS_KEY_ID=${AWS_KEY_ID}
      - AWS_SECRET=${AWS_SECRET}
    deploy:
      resources:
        limits:
          memory: 512 M
      restart_policy:
        condition: any
    container_name: webapp2
    ports:
      - "5002:5050"
    depends_on:
      localstack:
        condition: service_healthy

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "5050:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - webapp1
      - webapp2
