name: Deploy

on:
  push:
    branches:
      - main
    paths:
      - src/event_generator/**
      - src/web_app/**

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
        with:
          ref: main
      

      - name: setup docker buildx
        uses: docker/setup-buildx-action@v2
    
      - name: docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: build and push event_generator
        id: build-push-event-generator
        uses: docker/build-push-action@v3
        with:
          context: .
          file: src/event_generator/Dockerfile
          push: true
          tags: jfrcorrea/event_generator:latest
      
      - name: build and push web_app
        id: build-push-web-app
        uses: docker/build-push-action@v3
        with:
          context: .
          file: src/web_app/Dockerfile
          push: true
          tags: jfrcorrea/web_app:latest
